version: "0.1"

services:
  ns2-metrics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ns2-metrics
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"

volumes:
