{
 "title": "NS2-General",
 "description": "General Stats for NS2",
 "tags": [ "NS2" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Total Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current KD",
   "type": "table",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ns2_players{stat_type=\"kd\"}",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Current KDA",
   "type": "table",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "ns2_players{stat_type=\"kda\"}",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Maps Total Games",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 7, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ns2_maps", "legendFormat": "{{map}}" }
   ]
  },
  {
   "title": "Total Wins",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ns2_total_wins", "legendFormat": "{{race}}" }
   ]
  },
  {
   "title": "Player Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "map",
   "targets": [
    {}
   ]
  },
  {
   "title": "KD Series",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ns2_players{stat_type=\"kd\"}",
     "legendFormat": "{{player_name}}"
    }
   ]
  },
  {
   "title": "KDA Series",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "ns2_players{stat_type=\"kda\"}",
     "legendFormat": "{{player_name}}"
    }
   ]
  },
  {
   "title": "Kills",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "ns2_players{stat_type=\"kills\"}",
     "legendFormat": "{{player_name}}"
    }
   ]
  },
  {
   "title": "Assists",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "ns2_players{stat_type=\"assists\"}",
     "legendFormat": "{{player_name}}"
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "ns2_players{stat_type=\"deaths\"}",
     "legendFormat": "{{player_name}}"
    }
   ]
  },
  {
   "title": "Map Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Biodome",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_biodome\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Caged",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_caged\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Derelict",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_derelict\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Descent",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_descent\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Docking",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_docking\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Eclipse",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_eclipse\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Fusion",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_fusion\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Kodiak",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_kodiak\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Metro",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_metro\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Mineshaft",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_mineshaft\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Origin",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_origin\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Refinery",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_refinery\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Summit",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_summit\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Tanith",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_tanith\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Tram",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_tram\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Unearthed",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_unearthed\"}",
     "legendFormat": "{{race}}"
    }
   ]
  },
  {
   "title": "Veil",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ns2_map_wins{map=\"ns2_veil\"}",
     "legendFormat": "{{race}}"
    }
   ]
  }
 ]
}